# Generated by Django 4.2 on 2024-10-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_edited',
            new_name='is_edited',
        ),
    ]
