# Generated by Django 4.2 on 2024-12-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_rename_is_updateed_message_is_edited'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='chat',
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
