# Generated by Django 4.2 on 2024-10-06 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('find_house_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='users_app.customuser', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='find_house_app.announcement', verbose_name='Announcement'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.customuser', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='announcementviewhistory',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_house_app.announcement', verbose_name='Announcement'),
        ),
        migrations.AddField(
            model_name='announcementviewhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.customuser', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='announcementimage',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='find_house_app.announcement', verbose_name='Announcement'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='find_house_app.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.customuser', verbose_name='Owner'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'announcement')},
        ),
    ]
