# Generated by Django 4.2 on 2024-10-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_house_app', '0003_alter_announcement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'ACTIVE'), (2, 'SOLD'), (3, 'WITHDRAWN')], verbose_name='Status'),
        ),
    ]
