# Generated by Django 4.2 on 2024-10-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_house_app', '0004_alter_announcement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
    ]
