# Generated by Django 4.2 on 2024-10-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_house_app', '0005_alter_announcement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='Content'),
        ),
    ]
