# Generated by Django 4.2 on 2024-11-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_house_app', '0007_newscomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsComment',
        ),
    ]
