# Generated by Django 4.2 on 2024-12-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_house_app', '0009_alter_announcement_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
