# Generated by Django 4.2 on 2024-12-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_house_app', '0012_news_slug_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255, unique=True),
        ),
    ]
