# Generated by Django 4.2 on 2024-12-25 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts_page_h5', models.TextField(max_length=255, verbose_name='Contacts Page h5')),
                ('contacts_page_text', models.TextField(max_length=10000, verbose_name='Contacts Page Text')),
                ('contacts_page_address', models.TextField(max_length=255, verbose_name='Contacts Page Address')),
                ('contacts_page_telephone', models.TextField(max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contacts Page Telephone')),
                ('contacts_page_email', models.EmailField(max_length=255, verbose_name='Contacts Page Email')),
                ('footer_text', models.TextField(max_length=10000, verbose_name='Footer Text')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change Date')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
                'db_table': 'content',
                'ordering': ['change_date'],
            },
        ),
    ]
